#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Frank's aliases
alias n='ssh november'

# rbenv needs this
export PATH=~/.rbenv/shims:$PATH

# Chef
export CHEF_ENV=production
alias kne='knife node edit'
alias knl='knife node list'


# Defaults and co
export VISUAL=vim
export editor=$VISUAL

# Z because z
. /usr/local/etc/profile.d/z.sh
alias zz='z -l'
